
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _20171C_TP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TiposDocumento
{

    public TiposDocumento()
    {

        this.Reservas = new HashSet<Reserva>();

    }


    public int IdTipoDocumento { get; set; }

    public string Descripcion { get; set; }



    public virtual ICollection<Reserva> Reservas { get; set; }

}

}
