//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20171C_TP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versione
    {
        public Versione()
        {
            this.Carteleras = new HashSet<Cartelera>();
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int IdVersion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Cartelera> Carteleras { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
